name: beatbox
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.6
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  carousel_slider: ^4.2.1
  intl: ^0.19.0
  palette_generator: ^0.3.3+3
  http: ^1.2.0
  font_awesome_flutter: ^10.7.0
  just_audio: ^0.9.36
  custom_text: ^2.0.1
  animated_search_bar: ^2.7.1
  webview_flutter: ^4.7.0
  google_fonts: ^6.1.0
  intl_phone_field: ^3.2.0
  # flutter_login: ^5.0.0
  # firebase_core: ^2.24.2
  # firebase_auth: ^4.16.0


  
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/icons/
